//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoTcs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Rota = new HashSet<Rota>();
        }
    
        public int IDEmpresa { get; set; }
        public string NOME { get; set; }
        public string ENDERECO { get; set; }
        public System.TimeSpan INICIOATENDIMENTO { get; set; }
        public System.TimeSpan FIMATENDIMENTO { get; set; }
        public System.TimeSpan TEMPOVISITACAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rota> Rota { get; set; }
    }
}
